FROM ruby:3.2.2-alpine3.18

RUN apk update -qq && apk add libpq-dev nodejs vim g++ make

WORKDIR /workspace

ADD ../Gemfile /workspace/Gemfile
ADD ../Gemfile.lock /workspace/Gemfile.lock

RUN apk add --no-cache gcompat
RUN gem install bundler -v 2.4.19
RUN bundle install

# RUN  rails new _7.1.3.2_ . --database=postgresql --css=tailwind

CMD [ "rails", "s", "-b", "0.0.0.0" ]
